### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by lmakarov** [luiselizondo/docker-drupal-light#4]
I'm struggling with mysql here.
Looks like admin and user passwords are not being set properly during the container startup.
The generated passwords are not set and do not work.

```
web_1 | 141023 19:24:27 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
web_1 | Creating database
web_1 | ##########################################
web_1 | ########### INFORMATION USED #############
web_1 | ##########################################
web_1 | MYSQL_ROOT_PASSWORD: iek6Eekeepha
web_1 | MYSQL_DATABASE: drupal
web_1 | DRUPAL_USER: drupal
web_1 | DRUPAL_PASSWORD: Es5ya8Eigao1
web_1 | ##########################################
web_1 | ##########################################
web_1 | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
web_1 | Showing databases
web_1 | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
web_1 | Configuring root user
web_1 | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

**Comment by luiselizondo** [comment]
Hi, I'm actually not using this image anymore, there's a better way to do this.

First, you're gonna need to use fig but I guess you're already using it anyway.

With fig, you will create two containers, one for mysql and another for the web application (drupal).

For mysql, you can read a blog post I wrote a few weeks ago at http://luiselizondo.net/blogs/luis-elizondo/tutorial-how-use-mysql-docker it will help you understand and use the official MySQL docker image.

For the web application, I'm using my own image which you can find here: https://github.com/luiselizondo/nginx-php or at the docker registry you just do luis/nginx-php

I use that image everyday and I use it to run my drupal websites. The only thing I really haven't figured out is how to use Drush. I've been using Drush since it started and is hard not to use it anymore, but other than that, the image runs great. 

Don't forget to edit the settings.php file with getenv("SOME_VARIABLE") and you'll be fine. I will leave this issue open in case you have any further questions.

**Comment by lmakarov** [comment]
@luiselizondo do you have the details of the "better way" approach published anywhere?
This may save me some time figuring things out :)

**Comment by luiselizondo** [comment]
I did mention the approach, first, start by reading the blog post on how to use MySQL with Docker, then use the image luis/nginx-php

If what you want is the fig.yml file I'm using, then here it is:

'''
mysql:
  image: mysql
  expose:
    - "3306"
  volumes_from:
    - DRUPAL_MYSQL_1_DATA
  environment:
    MYSQL_ROOT_PASSWORD: 123
web:
  image: luis/nginx-php
  volumes:
    - "./:/var/www"
    - "/var/log/docker/drupal:/var/log/supervisor"
  ports:
    - "80:80"
  links:
    - "mysql:mysql"
'''

You'll have to first create the mysql container using the scripts I mention in the blog since fig will not create the data-only container.

**Comment by lmakarov** [comment]
@luiselizondo thanks.
I pretty much ended up with the same fig.yml file and added some enhancements

```
web:
  image: luis/nginx-php
  ports:
    - "80:80"
  volumes:
    - "./docroot:/var/www"
  links:
    - "db:mysql"
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=123
    - MYSQL_DATABASE=drupal
  volumes_from:
    - mysql_dbdata
```

Then created a data-only container for mysql: `docker run -d -v /var/lib/mysql --name mysql_dbdata busybox`

I really like how the mysql image can provision the DB username/password/database automatically from the ENV variables.

DB connection setting in settings.php:

```
$databases = array (
  'default' => 
  array (
    'default' => 
    array (
      'database' => $_SERVER['MYSQL_ENV_MYSQL_DATABASE'],
      'username' => $_SERVER['MYSQL_ENV_MYSQL_USER'],
      'password' => $_SERVER['MYSQL_ENV_MYSQL_PASSWORD'],
      'host' => $_SERVER['MYSQL_PORT_3306_TCP_ADDR'],
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
```

Hope this helps someone and thanks for a kick-start.

**Comment by luiselizondo** [comment]
Instead of using $_SERVER to get the environment variables you should use get_env()

I didn't know you could use the MySQL official docker image to create a database and a user automatically but that's good to know    

Luis Elizondo

**Comment by lmakarov** [comment]
What's the benefit/difference in using getenv() vs $_SERVER superglobal?

**Comment by luiselizondo** [comment]
There’s really no big difference according to the PHP Manual, you can use either and it’s fine. Probably one of the main differences is that with $_SERVER is “easy” to override a configuration since is just a variable and with getenv() is just not possible since is just a getter. Whatever works for you is fine.
